### ISSUE TITLE
Perfomance monitoring

### ISSUE THREAD

**Issue by tomjirsa** [CSIRT-MU/Stream4Flow#2] opened 2017-02-08 08:15 UTC
Integrate tools for Stream4Flow performance monitoring.

Use test example on kafka:

- [x] Install plugin for monitoring kafka for graphite from [here](https://github.com/damienclaveau/kafka-graphite)
- [x] Configure logstash to recieve data from monitoring plugin
- [x] Store data from logstash to elasticsearch into a specifics index called `monitoring-*`
- [ ] Present results

**Comment by simkosvorad** [comment] 2017-04-28 12:26
The plugin you have recommended is supposed to work with kafka 0.8.x and 0.9.x versions but we are using 0.10.0 version now. Maybe [this](https://github.com/apakulov/kafka-graphite) would be usable with a few changes.

**Comment by simkosvorad** [comment] 2017-05-12 14:17
I tried the plugin above but couldn't figure out the proper installation with gradlew. So Tom recommended [this](https://github.com/damienclaveau/kafka-graphite) since it can be easily done with maven. I configured kafka and logstash but no metrics were received by elasticsearch. I don't know where the problem yet ,if no data are  sent or just loggstash isn't receiving them.

**Comment by simkosvorad** [comment] 2017-05-19 08:55
I tried the plugin above but couldn't figure out the proper installation with gradlew. So Tom recommended [this](https://github.com/damienclaveau/kafka-graphite) since it can be easily done with maven. I configured kafka and logstash but no metrics were received by elasticsearch. I don't know where the problem yet ,if no data are  sent or just loggstash isn't receiving them.

**Comment by simkosvorad** [comment] 2017-05-22 13:57
Managed to make it work, ELK stack is now receiving most of the kafka metrics but not all of them as pointed in [issue](https://github.com/damienclaveau/kafka-graphite/issues/23) to the plugin.

**Comment by simkosvorad** [comment] 2017-05-29 13:40
Manager to configure reporter to send server metrics, but i wasn't abe to exclude any of them so far.

**Comment by simkosvorad** [comment] 2017-06-02 14:11
I figured out the including/excluding of metrics so now I need you to specify what exactly should be monitored so i could exclude unnecessary metrics.

**Comment by simkosvorad** [comment] 2017-06-16 13:58
I tried both of stated plugins but both of them have their pros/cons . The [https://github.com/apakulov/kafka-graphite](first) one reports all metrics can be filtered in a minimal way, on the other hand the [https://github.com/damienclaveau/kafka-graphite](second) one can be filtered easily in much bigger scale but doesn't report all of the metrics, some of which are neccessary for us i.e. BytesInPerSecond, BytesOutPerSecond. So I decided to use the first plugin reporting all of the metrics and try to filter them in logstash (with no success so far). Also i need wanted metrics to be specified, so i know what exclude and focus on that rather than blindly excluding random things, just to figure out how it could be done.

**Comment by simkosvorad** [comment] 2017-07-07 10:14
Few days ago the plugin that was intended to be used got na update to support kafka version 0.10.X, after the update I'm now not able to build the plugin. I have tried to build it on my computer, on liber-root server and on producer but with no success. Can someone please try building [the plugin](https://github.com/apakulov/kafka-graphite) on their device so i could know if the problem is on my side or it is the plugin. All my atempts ended with errors like 
`/home/spark/kafka-graphite/kafka-graphite/src/main/scala/kafka/metrics/KafkaGraphiteMetricsReporter.scala:23: object GraphiteReporter is not a member of package com.yammer.metrics.reporting ` I can't find the problem causing this because according to [this](http://metrics.dropwizard.io/2.2.0/apidocs/com/yammer/metrics/reporting/GraphiteReporter.html) the package is correct.

**Comment by tomjirsa** [comment] 2017-07-10 12:54
@xdanos  - could you please look into the compilation issue above? - you're expert in java, scala... Thx.

**Comment by xdanos** [comment] 2017-07-11 06:47
I'll look into it today.

**Comment by xdanos** [comment] 2017-07-11 14:50
Add the following line:
```compile 'com.yammer.metrics:metrics-graphite:2.2.0``` 
into Gradle build configuration tag
```project(':kafka-graphite') {dependencies {*HERE*}}```
in file
[build.gradle](https://github.com/apakulov/kafka-graphite/blob/master/build.gradle)

IF it works, file an Issue in the Github project of the plugin

**Comment by simkosvorad** [comment] 2017-07-14 14:37
Your advice fixed the problem with building the .jar file, however the code still doesn't work, due to exceptions thrown by the plugin when trying to start kafka. The exception is the same  `Caused by: java.lang.ClassNotFoundException: com.yammer.metrics.reporting.GraphiteReporter`.

**Comment by xdanos** [comment] 2017-07-16 07:37
It is a dependency problem:
A. you must include all of the dependencies in Kafka's classpath
B. you must create FAT JAR with gradle that includes all of this dependencies in a single file

**Comment by cermmik** [comment] 2018-05-22 08:53
Currently outdated. Closing the issue.

**Closed as completed by cermmik** 2018-05-22 08:53 UTC
Labels: type:enhancement, info:help wanted, prio:medium, status:in-progress
